// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAlertRule(arg1:models.AlertRule):Promise<models.AlertRule>;

export function ChangeEncryptionPassword(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdate():Promise<models.UpdateInfo>;

export function ClearAlertHistory():Promise<void>;

export function ClearDatabase():Promise<void>;

export function ClearMessages():Promise<void>;

export function CompactDatabase():Promise<void>;

export function DeleteAlertRule(arg1:string):Promise<boolean>;

export function DisableEncryption(arg1:string):Promise<void>;

export function EnableEncryption(arg1:string):Promise<void>;

export function ExportCACertificate():Promise<string>;

export function ExportCertificate():Promise<string>;

export function ExportLogs(arg1:models.FilterCriteria,arg2:string):Promise<string>;

export function ExportServerCertificate():Promise<string>;

export function GenerateCA(arg1:models.CertOptions):Promise<models.CertInfo>;

export function GenerateCertificate(arg1:models.CertOptions):Promise<models.CertInfo>;

export function GenerateServerCert(arg1:models.CertOptions):Promise<models.CertInfo>;

export function GetAlertHistory():Promise<Array<models.AlertEvent>>;

export function GetAlertRules():Promise<Array<models.AlertRule>>;

export function GetAppVersion():Promise<string>;

export function GetCACertInfo():Promise<models.CertInfo>;

export function GetCertificateInfo(arg1:models.ServerConfig):Promise<models.CertInfo>;

export function GetDefaultCertOptions():Promise<models.CertOptions>;

export function GetDefaultConfig():Promise<models.ServerConfig>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetMessages(arg1:models.FilterCriteria):Promise<Array<models.SyslogMessage>>;

export function GetServerCertInfo():Promise<models.CertInfo>;

export function GetServerStatus():Promise<models.ServerStatus>;

export function GetStats():Promise<models.ServerStats>;

export function GetStorageConfig():Promise<models.StorageConfig>;

export function GetStorageStats():Promise<models.StorageStats>;

export function GetUnlockAttemptsRemaining():Promise<number>;

export function IsEncryptionEnabled():Promise<boolean>;

export function IsEncryptionLocked():Promise<boolean>;

export function IsStorageReady():Promise<boolean>;

export function QueryMessageGroups(arg1:models.FilterCriteria,arg2:string):Promise<Array<models.GroupSummary>>;

export function QueryMessages(arg1:models.QueryOptions):Promise<models.PagedResult>;

export function SelectCAFile():Promise<string>;

export function SelectCertFile():Promise<string>;

export function SelectKeyFile():Promise<string>;

export function SetStorageConfig(arg1:models.StorageConfig):Promise<void>;

export function StartServer(arg1:models.ServerConfig):Promise<void>;

export function StopServer():Promise<void>;

export function UnlockDatabase(arg1:string):Promise<void>;

export function UpdateAlertRule(arg1:models.AlertRule):Promise<boolean>;
