// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAlertRule(arg1) {
  return window['go']['main']['App']['AddAlertRule'](arg1);
}

export function ChangeEncryptionPassword(arg1, arg2) {
  return window['go']['main']['App']['ChangeEncryptionPassword'](arg1, arg2);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearAlertHistory() {
  return window['go']['main']['App']['ClearAlertHistory']();
}

export function ClearDatabase() {
  return window['go']['main']['App']['ClearDatabase']();
}

export function ClearMessages() {
  return window['go']['main']['App']['ClearMessages']();
}

export function CompactDatabase() {
  return window['go']['main']['App']['CompactDatabase']();
}

export function DeleteAlertRule(arg1) {
  return window['go']['main']['App']['DeleteAlertRule'](arg1);
}

export function DisableEncryption(arg1) {
  return window['go']['main']['App']['DisableEncryption'](arg1);
}

export function EnableEncryption(arg1) {
  return window['go']['main']['App']['EnableEncryption'](arg1);
}

export function ExportCACertificate() {
  return window['go']['main']['App']['ExportCACertificate']();
}

export function ExportCertificate() {
  return window['go']['main']['App']['ExportCertificate']();
}

export function ExportLogs(arg1, arg2) {
  return window['go']['main']['App']['ExportLogs'](arg1, arg2);
}

export function ExportServerCertificate() {
  return window['go']['main']['App']['ExportServerCertificate']();
}

export function GenerateCA(arg1) {
  return window['go']['main']['App']['GenerateCA'](arg1);
}

export function GenerateCertificate(arg1) {
  return window['go']['main']['App']['GenerateCertificate'](arg1);
}

export function GenerateServerCert(arg1) {
  return window['go']['main']['App']['GenerateServerCert'](arg1);
}

export function GetAlertHistory() {
  return window['go']['main']['App']['GetAlertHistory']();
}

export function GetAlertRules() {
  return window['go']['main']['App']['GetAlertRules']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCACertInfo() {
  return window['go']['main']['App']['GetCACertInfo']();
}

export function GetCertificateInfo(arg1) {
  return window['go']['main']['App']['GetCertificateInfo'](arg1);
}

export function GetDefaultCertOptions() {
  return window['go']['main']['App']['GetDefaultCertOptions']();
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetServerCertInfo() {
  return window['go']['main']['App']['GetServerCertInfo']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStorageConfig() {
  return window['go']['main']['App']['GetStorageConfig']();
}

export function GetStorageStats() {
  return window['go']['main']['App']['GetStorageStats']();
}

export function GetUnlockAttemptsRemaining() {
  return window['go']['main']['App']['GetUnlockAttemptsRemaining']();
}

export function IsEncryptionEnabled() {
  return window['go']['main']['App']['IsEncryptionEnabled']();
}

export function IsEncryptionLocked() {
  return window['go']['main']['App']['IsEncryptionLocked']();
}

export function IsStorageReady() {
  return window['go']['main']['App']['IsStorageReady']();
}

export function QueryMessageGroups(arg1, arg2) {
  return window['go']['main']['App']['QueryMessageGroups'](arg1, arg2);
}

export function QueryMessages(arg1) {
  return window['go']['main']['App']['QueryMessages'](arg1);
}

export function SelectCAFile() {
  return window['go']['main']['App']['SelectCAFile']();
}

export function SelectCertFile() {
  return window['go']['main']['App']['SelectCertFile']();
}

export function SelectKeyFile() {
  return window['go']['main']['App']['SelectKeyFile']();
}

export function SetStorageConfig(arg1) {
  return window['go']['main']['App']['SetStorageConfig'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UnlockDatabase(arg1) {
  return window['go']['main']['App']['UnlockDatabase'](arg1);
}

export function UpdateAlertRule(arg1) {
  return window['go']['main']['App']['UpdateAlertRule'](arg1);
}
