// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAlertRule(arg1:main.AlertRule):Promise<main.AlertRule>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearAlertHistory():Promise<void>;

export function ClearDatabase():Promise<void>;

export function ClearMessages():Promise<void>;

export function CompactDatabase():Promise<void>;

export function DeleteAlertRule(arg1:string):Promise<boolean>;

export function ExportCACertificate():Promise<string>;

export function ExportCertificate():Promise<string>;

export function ExportLogs(arg1:main.FilterCriteria,arg2:string):Promise<string>;

export function ExportServerCertificate():Promise<string>;

export function GenerateCA(arg1:main.CertOptions):Promise<main.CertInfo>;

export function GenerateCertificate(arg1:main.CertOptions):Promise<main.CertInfo>;

export function GenerateServerCert(arg1:main.CertOptions):Promise<main.CertInfo>;

export function GetAlertHistory():Promise<Array<main.AlertEvent>>;

export function GetAlertRules():Promise<Array<main.AlertRule>>;

export function GetAppVersion():Promise<string>;

export function GetCACertInfo():Promise<main.CertInfo>;

export function GetCertificateInfo(arg1:main.ServerConfig):Promise<main.CertInfo>;

export function GetDefaultCertOptions():Promise<main.CertOptions>;

export function GetDefaultConfig():Promise<main.ServerConfig>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetMessages(arg1:main.FilterCriteria):Promise<Array<main.SyslogMessage>>;

export function GetServerCertInfo():Promise<main.CertInfo>;

export function GetServerStatus():Promise<main.ServerStatus>;

export function GetStats():Promise<main.ServerStats>;

export function GetStorageConfig():Promise<main.StorageConfig>;

export function GetStorageStats():Promise<main.StorageStats>;

export function QueryMessageGroups(arg1:main.FilterCriteria,arg2:string):Promise<Array<main.GroupSummary>>;

export function QueryMessages(arg1:main.QueryOptions):Promise<main.PagedResult>;

export function SelectCAFile():Promise<string>;

export function SelectCertFile():Promise<string>;

export function SelectKeyFile():Promise<string>;

export function SetStorageConfig(arg1:main.StorageConfig):Promise<void>;

export function StartServer(arg1:main.ServerConfig):Promise<void>;

export function StopServer():Promise<void>;

export function UpdateAlertRule(arg1:main.AlertRule):Promise<boolean>;
