// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {notify} from '../models';
import {importer} from '../models';

export function AddAlertRule(arg1:models.AlertRule):Promise<models.AlertRule>;

export function AreSinkCredentialsUnencrypted():Promise<boolean>;

export function CancelClose():Promise<void>;

export function ChangeEncryptionPassword(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdate():Promise<models.UpdateInfo>;

export function ClearAlertHistory():Promise<void>;

export function ClearDatabase():Promise<void>;

export function ClearMessages():Promise<void>;

export function ClearNotifyLog():Promise<void>;

export function CompactDatabase():Promise<void>;

export function DeleteAlertRule(arg1:string):Promise<boolean>;

export function DeleteNotifyRoute(arg1:string):Promise<void>;

export function DeleteNotifySink(arg1:string):Promise<void>;

export function DisableEncryption(arg1:string):Promise<void>;

export function DownloadAndApplyUpdate():Promise<void>;

export function EnableEncryption(arg1:string):Promise<void>;

export function ExportCACertificate():Promise<string>;

export function ExportCertificate():Promise<string>;

export function ExportLogs(arg1:models.FilterCriteria,arg2:string,arg3:string):Promise<string>;

export function ExportServerCertificate():Promise<string>;

export function GenerateCA(arg1:models.CertOptions):Promise<models.CertInfo>;

export function GenerateCertificate(arg1:models.CertOptions):Promise<models.CertInfo>;

export function GenerateServerCert(arg1:models.CertOptions):Promise<models.CertInfo>;

export function GetAlertHistory():Promise<Array<models.AlertEvent>>;

export function GetAlertRules():Promise<Array<models.AlertRule>>;

export function GetAppVersion():Promise<string>;

export function GetCACertInfo():Promise<models.CertInfo>;

export function GetCertificateInfo(arg1:models.ServerConfig):Promise<models.CertInfo>;

export function GetCloseAction():Promise<string>;

export function GetDefaultCertOptions():Promise<models.CertOptions>;

export function GetDefaultConfig():Promise<models.ServerConfig>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetMessages(arg1:models.FilterCriteria):Promise<Array<models.SyslogMessage>>;

export function GetNetworkInterfaces():Promise<Array<models.NetworkInterface>>;

export function GetNotifyLog():Promise<Array<notify.DeliveryEntry>>;

export function GetNotifyRoutes():Promise<Array<notify.Route>>;

export function GetNotifySinks():Promise<Array<notify.SinkConfig>>;

export function GetNotifyStats():Promise<notify.Stats>;

export function GetScenarioDurationSeconds():Promise<number>;

export function GetServerCertInfo():Promise<models.CertInfo>;

export function GetServerStatus():Promise<models.ServerStatus>;

export function GetSimulatorConfig():Promise<models.SimulatorConfig>;

export function GetSimulatorStatus():Promise<models.SimulatorStatus>;

export function GetStats():Promise<models.ServerStats>;

export function GetStorageConfig():Promise<models.StorageConfig>;

export function GetStorageStats():Promise<models.StorageStats>;

export function GetUnlockAttemptsRemaining():Promise<number>;

export function GetUnlockLockoutSeconds():Promise<number>;

export function GetUpdateConfig():Promise<models.UpdateConfig>;

export function HideToBackground():Promise<void>;

export function ImportLogFile(arg1:string,arg2:boolean):Promise<importer.Result>;

export function IsCAKeyUnencrypted():Promise<boolean>;

export function IsEncryptionEnabled():Promise<boolean>;

export function IsEncryptionLocked():Promise<boolean>;

export function IsStorageReady():Promise<boolean>;

export function IsTrayAvailable():Promise<boolean>;

export function LoadPersistedCA():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PreviewLogFile(arg1:string):Promise<importer.Preview>;

export function QueryMessageGroups(arg1:models.FilterCriteria,arg2:string):Promise<Array<models.GroupSummary>>;

export function QueryMessages(arg1:models.QueryOptions):Promise<models.PagedResult>;

export function QuitApplication():Promise<void>;

export function RevealWindow():Promise<void>;

export function SaveNotifyRoute(arg1:notify.Route):Promise<void>;

export function SaveNotifySink(arg1:notify.SinkConfig):Promise<void>;

export function SaveSimulatorConfig(arg1:models.SimulatorConfig):Promise<void>;

export function SelectCAFile():Promise<string>;

export function SelectCertFile():Promise<string>;

export function SelectKeyFile():Promise<string>;

export function SelectLogFile():Promise<string>;

export function SetCloseAction(arg1:string):Promise<void>;

export function SetStorageConfig(arg1:models.StorageConfig):Promise<void>;

export function SetTrayLabels(arg1:string,arg2:string):Promise<void>;

export function SetUpdateConfig(arg1:models.UpdateConfig):Promise<void>;

export function SkipUpdateVersion(arg1:string):Promise<void>;

export function StartServer(arg1:models.ServerConfig):Promise<void>;

export function StartSimulator(arg1:models.SimulatorConfig):Promise<void>;

export function StopServer():Promise<void>;

export function StopSimulator():Promise<void>;

export function TestNotifySink(arg1:notify.SinkConfig):Promise<void>;

export function UnlockDatabase(arg1:string):Promise<void>;

export function UpdateAlertRule(arg1:models.AlertRule):Promise<boolean>;
